"""
These observations are those that contained the most alerts using EXOD.

I have gone through them all and manually selected those that are a result
of bad data, in a lot of cases, many spurious alerts are generated by the
presence of extended sources, such as galaxy clusters or supernova remnants.
"""

obsids_to_exclude = ['0690700201', # Puppis A  # Comet C/2009 P1 (Garradd)
                     '0162360601', # Vela SNR
                     '0781870101', # Puppis A
                     '0300960201', # Comet 9P/Tempel 1
                     '0162360101', # Vela SNR
                     '0672160601', # Comet C/2009 P1 (Garradd)
                     '0150150301', # Puppis A
                     '0650220901', # Puppis A
                     '0880280301', # Ophiuchus cluster
                     '0650221001', # Puppis A
                     '0811213001', # C/2016 R2 (PanSTARRS)
                     '0693400101', # Cygnus Loop
                     '0124100101', # Neutron Star RX J0720.4-3125 (shoddy data)
                     '0880280701', # !!! Ophiuchus cluster W (These is a possible burst in this!!!!!)  	17h13m53.41s 	-23d20m50.86s 	258.472541 	-23.347462
                     '0650221201', # Puppis A
                     '0742040201', # Puppis A
                     '0650221401', # Puppis A
                     '0650221301', # Puppis A
                     '0722640301', # Puppis A
                     '0149880101', # A2034 Cluster (utter crap)
                     '0113020301', # Puppis A
                     '0103461135', # C2000 WM1 Mosaic Observation
                     '0124711401', # Coma Cluster
                     '0650221101', # Puppis A
                     '0883630101', # RXC J0303.8-7752 Cluster
                     '0657600201', # Puppis A
                     '0880280401', # Ophiuchus cluster S
                     # '0881910101', # IDCS J1426.5+3508 Cluster  (high redshift, maybe we keep this)
                     # '0900170101', # NGC4594 (nearby spiral, maybe keep)
                     '0122340401', # GX13+1 (This is a type 1 burster but the data is horrific)
                     '0862670101', # XLSSC 105 merging cluster
                     '0305800201', # MZ 3541 Galaxy Group
                     '0722640401', # Puppis A
                     '0555630301', # SN 1006
                     '0884710101', # SPT-CLJ2228-5828 cluster merger
                     '0164570601', # GRB 050223 Lots of spurious stuff at the end of the observation.
                     '0880280101', # Ophiuchus cluster N (Few real stellar flares in here)
                     '0112951501', # A2256_f5 Merging cluster
                     '0882110401', # Jupiter (Moving Target)
                     '0202080201', # A2065 Cluster
                     '0108460101', # Abell 1775 Cluster
                     '0403200101', # Orion Nebula cluster (maybe keep this there's so much in here)
                     '0843890101', # (!!!!!!!! Large burst!!!))     Hydra A  9h17m32.56s	-11d58m27.70s	139.385649	-11.974361
                     '0141380201', # Abell 2256 Cluster
                     '0605540101', # AWM 7 Cluster (1 stellar flare in here)
                     '0504810101', # RCW 86 NE SNR
                     '0723801001', # Abell 4059 (Possible outburst in a real source near end of obs 23h57m11.25s	-34d48m01.60s	359.296876	-34.800443)
                     # '0300310401', # PG 1535+547 (maybe keep)
                     '0723801301', # Abell 133 Cluster
                     '0880810101', # RXJ0821 Cluster
                     # '0674210601', # M31 andromeda (keep)
                     '0744450301', # RBS 229 (end of obs)
                     '0723800501', # NGC 1550 cluster
                     '0864110101', # MRC 0116+111 Cluster
                     '0760940101', # Bullet Cluster (some real stuff)
                     '0801840501', # Tycho SE knots
                     '0096210101', # Tycho SNR (test observation horrible)
                     # '0800031001', # Elias 29 (keep)
                     '0310590201', # Tycho SNR Calibration (horrible)
                     # '0760900101', # Rho Ophiuchi (keep)
                     '0842812001', # Jupiter
                     '0412380101', # Tycho SNR Calibration
                     '0310590101', # Tycho SNR Calibration
                     # '0800031001', # Elias 29 (Keep)
                     '0093000101', # OMC3 (keep)
                     '0723800901', # Abell 4059 Cluster
                     # '0882340601', # Mrk 817 (keep)
                     # '0864110201', # MRC 0116+111 (keep)
                     # '0305540701', # rho Oph SFR (keep)
                     # '0800030901', # Elias 29 (keep)
                     # '0600980101', # X Persei (very bright keep)
                     '0305780101', # Perseus Cluster
                     '0801930801', # Jupiter (stop pointing the telescope at planets at this thing god damn it you already broke the thing once)
                     '0089370701', # Saturn (really guys?)
                     # '0843890301', # Hydra A cluster (keep)
                     # '0800030801', # Elias 29 (keep)
                     # '0844210101', # MOO J1142+1527 Cluster (keep) (also Moo!)
                     '0801840201', # Tycho SE knots 
                     '0674440101', # PSR J0357+32 (end of obs spurious)
                     # '0402430301', # Sgr A* Absolutely crazy (keep)
                     # '0862670201', # XLSSC 105 merging cluster (not great but keep)
                     '0412380201', # Tycho SNR (I swear to god)
                     # '0305541101', # rho Oph (keep)
                     # '0302850201', # MCG-5-23-16 Seyfert 1 (keep)
                     # '0824730201', # (!!!!big bursts!) NS MAXI J0556-332 (keep) 5h57m33.49s	-33d01m11.20s	89.389556	-33.019777
                     # '0605900101', # Orion Nebula (keep)
                     '0200920101', # M87 (very bright)
                     '0882110601', # Jupiter
                     '0600540601', # Mkn 335 (Seyfert 1) (bad end but keep)
                     '0823580701', # Centaurus cluster Real burst at 12h48m39.09s 	-41d15m26.90s 	192.162883 	-41.257473
                     '0842811001', # Jupiter
                     '0008820401', # HD168112 very strange spuricous spike
                     '0881210201', # 1E 2216/2215 SE cluster outskirts (lots of crap but check 0881210201_0_5_0.2_2.0 (9) 22h18m29.61s	-4d12m24.35s	334.623370	-4.206764)
                     '0901910101', # ACT-CLJ0012-0855/J0 merging cluster (1 stellar flare but nothing else)
                     '0097610801', # Cas A (horrible)
                     # '0822340301', # NGC 6482 elliptical (keep)
                     '0903710201', # M87
                     # '0123900101', # A S 1101 Galaxy Cluster (two interesting bursts keep)
                     # '0501790101'  # NGC 2547 SFR (keep)
                     # '0871190401', # 0871190401 (keep)
                     # '0200960101', # XY UMA (CV) (keep) (end of obs is bad)
                     '0110012701', # MSH 11-54 SNR 
                     # '0911990201', # Mrk 817 (keep)
                     # '0885090101', # NGC 6814 (keep)
                     # '0780561501', # IRAS13224-3809 Seyfert 1 (keep)
                     '0801930901', # Jupiter
                     # '0872390901', # Mrk 817 (keep)
                     '0200080701', # JUPITER
                     '0723801001', # Abell 4059 Cluster
                     # '0118700601', # EXO0748-67 (keep)
                     # '0152780201', # 4U 1538-522 HMXB (keep)
                     # '0741280201', # Mrk 335 NLS1 (keep)
                     '0110010301', # Cas A (steaming pile of dog crap)
                     '0741820101', # Cygnus Loop P7 (i don't need it!)
                     # '0852980601', # Clumpy structure (keep)
                     '0842550101', # Kepler SNR (there is a hard 2-12 flare at 0842550101_0_5_2.0_12.0 	0 	17h31m13.15s 	-21d25m51.82s 	262.804773 	-21.431060)
                     '0110010201', # Cas A (S) (horrific)
                     # '0790381501', # 1ES 1553+113 AGN (keep)
                     '0880280501', # Ophiuchus cluster (1 stellar flare)
                     # '0881210101', # 1E 2216/2215 SE (keep)
                     # '0202670601', # SGR A* (keep)
                     '0504260101', # Hydra A Cluster
                     # '0123500101', # EXO0748-676 (LMC) (keep)
                     '0880280201', # Ophiuchus cluster E (double stellar flare)
                     # '0655050101', # NGC55 ULX (keep)
                     # '0863050201', # ESO 033-G002 (keep)
                     # '0825140101', # Sgr E (keep)
                     # '0761630201', # Virgo Cluster galaxy NGC 4472 (lots of sketchy stuff at 200s but we'll keep it)
                     '0823580801', # Centaurus cluster (there is 1 fairly big 1 bin burst at  0823580801_0_5_0.2_2.0	8	12h50m31.72s	-41d09m58.41s	192.632154	-41.166224)
                     '0147800201', # 2A 0335+096 cluster
                     '0723800801', # Abell 4038 (there is a recurring single bin bright transient in this, likely spuricious) 23h47m26.47s 	-28d22m20.56s 	356.860312 	-28.372378
                     '0842811501', # Jupiter (go away)
                     '0108460101', # Abell 1775 (junk)
                     '0110011001', # Cas A (calibration obs)
                     # '0884620101', # SNR DEM L71 (keep)
                     '0109070201', # E1346+266 (Cluster nearby)
                     '0723800301', # NGC 507 Cluster
                     # '0511580401', # 1H0707-495 TOO (keep)
                     '0744450101', # RBS 1055 Quazar (end of obs bad)
                     '0880810101', # RX J0820.9+0752 Cluster
                     # '0652250101', # EZ CMa (WR) (keep)
                     '0511580201', # 1H0707-495
                     # '0556260301', # WR 133 (keep)
                     '0117900901', # EXO0748-67 (keep)
                     # '0503560301', # Orion A3 Hard Flare! (keep)
                     '0840580301', # Abell 1664 Cluster
                     # '0803671101', # Virgo (offset) (!!!! Very large flare!!!, but also lots of junk (keep))  	12h30m20.24s 	12d28m45.41s 	187.584345 	12.479280
                     '0744340101', # PKS 0745-191 Cluster
                     # '0863890201', # CXOU J132552.8-4305 (Cen A in FOV) (keep) lots of good stuff
                     '0605540201', # Zw3146 Cluster 
                     '0504810101', # SN 185
                     # '0206080101', # M82 (very janky but keep)
                     '0821250501', # 3XLSSJ021325-042000 (keep)
                     '0762470101', # Abell 2443 Cluster
                     # '0554680101', # NGC 5044 (keep)
                     # '0790380901', # 1ES 1553+113 (keep)
                     # '0671960101', # SU+AB Aur (YSO) (keep)
                     # '0604860201', # V4046 Sgr (keep)
                     # '0011450101', # SMC X-1 (janky but keep)
                     # '0151380101', # X Persei (janky but keep)
                     # '0885180101', # NGC5055 ULX1 (keep)
                     # '0694670101', # NGC 1380 ULX (keep)
                     # '0152020101', # NGC 253 (lots of diffuse emission but keep)
                     '0761070201', # Abell 523 Cluster (1 real flare at 200s)
                     '0782150101', # A370 Cluster
                     '0122340601', # GX13+1 off5 (calibration)
                     # '0881910201', # IDCS J1426.5+3508 high redshift GC (keep)
                     # '0671930101', # V407 Cyg (keep)
                     '0511180101', # Tycho SNR
                     # '0502050101', # QSO PG1211+143 (keep)
                     # '0891801701', # WISEA J045649.8-2037 (keep)
                     # '0650510201', # M33 (keep) (AGN switches off halfway through obs!?  	1h33m33.52s 	30d32m09.60s 	23.389648 	30.536001)
                     # '0824610401', # AGN NGC4395 (keep)
                     # '0821722001', # ACT-CL J2152.9-0114 (keep)
                     '0675060101', # J060313.4+421231 cluster-like (radio relic) (don't trust it)
                     # '0883550201', # M51 ULX-7 (keep)
                     '0822200101', # 3C196.1 Cluster (few flares in here)
                     # '0652250501', # EZ CMa (WR6) (keep)
                     # '0604960801', # CDFS (keep)
                     # '0721620101', # Praesepe-Field 1 (keep)
                     # '0883550101', # M51 ULX-7 (grim obs but keep)
                     # '0803990201', # NGC 1313 X-1 (big flare :o  	3h17m44.97s 	-66d37m41.75s 	49.437383 	-66.628264) (keep)
                     # '0827320601', # PSZ2G066.41+27.03 Cluster (janky but keep)
                     # '0653510301', # 1H0707-495 (AGN) (keep)
                     '0653380501', # NGC 5408 X-1 pretty wild stellar flare (keep)
                     # '0653380301', # NGC 5408 X-1 (keep)
                     # '0862730301', # ILTJ133729.25+48182 (keep)
                     '0722430101', # Nothing intrinsically wrong with this one but something near the edge of the CCD results in a 3 big spikes
                     '0823432701', # 21P/Giacobini-Zinne Comet
                     '0748591133', # C2014 Q2 Lovejoy Comet
                     '0748591134', # C2014 Q2 Lovejoy Comet
                     '0882110501' # Jupiter
                     '0200080734', # Jupiter
                     '0200080733', # Jupiter
                     '0200080732', # Jupiter
                     '0200080731', # Jupiter
                     '0200080234', # Jupiter
                     '0200080233', # Jupiter
                     '0200080232', # Jupiter
                     '0200080231', # Jupiter
                     '0882110601', # Jupiter
                     '0882110501', # Jupiter
                     '0882110401', # Jupiter
                     '0842812001', # Jupiter
                     '0801931901', # Jupiter
                     '0413780401', # Jupiter
                     '0413780301', # Jupiter
                     '0413780201', # Jupiter
                     '0413780101', # Jupiter
                     '0842811501', # Jupiter
                     '0842811001', # Jupiter
                     '0801931001', # Jupiter
                     '0801931801', # Jupiter
                     '0801931101', # Jupiter
                     '0801930901', # Jupiter
                     '0801930801', # Jupiter
                     '0801930701', # Jupiter
                     '0781830601', # Jupiter
                     '0781830301', # Jupiter
                     '0158761201', # Jupiter
                     '0158760140', # Jupiter
                     '0158760139', # Jupiter
                     '0158760138', # Jupiter
                     '0158760137', # Jupiter
                     '0158760135', # Jupiter
                     '0158760134', # Jupiter
                     '0158760133', # Jupiter
                     '0158760132', # Jupiter
                     '0158760131', # Jupiter
                     '0728960832', # Jupiter
                     '0728960831', # Jupiter
                     '0728960632', # Jupiter
                     '0728960631', # Jupiter
                     '0103461135', # Comet C2000 WM1	
                     '0103461136', # Comet C2000 WM1	
                     '0164960101', # Comet C2001 Q4 
                     '0113040701', # Comet C2001/A2 
                     '0113040801', # Comet C2001/A2 
                     '0113040901', # Comet C2001/A2 
                     '0113041301', # Comet C2001_Q4 
                     '0677981001', # Comet C2009 P1 
                     '0677981101', # Comet C2009 P1 
                     '0724790401', # Comet C2011 L4 
                     '0724790501', # Comet C2011 L4 
                     '0724790601', # Comet C2011 L4 
                     '0724790731', # Comet C2011 L4 
                     '0724790732', # Comet C2011 L4 
                     '0748590131', # Comet C2013 A1 
                     '0748590132', # Comet C2013 A1 
                     '0748590133', # Comet C2013 A1 
                     '0748590134', # Comet C2013 A1 
                     '0748590135', # Comet C2013 A1 
                     '0748590136', # Comet C2013 A1 
                     '0748590137', # Comet C2013 A1 
                     '0748590138', # Comet C2013 A1 
                     '0748590139', # Comet C2013 A1 
                     '0748591131', # Comet C2014 Q2 Lovejoy	
                     '0748591132', # Comet C2014 Q2 Lovejoy	
                     '0748591133', # Comet C2014 Q2 Lovejoy	
                     '0748591134', # Comet C2014 Q2 Lovejoy	
                     '0748591135', # Comet C2014 Q2 Lovejoy	
                     '0748591136', # Comet C2014 Q2 Lovejoy	
                     '0811213001', # Comet C2016 R2 PANSTARRS	
                     '0701980733', # Comet C 2012 F6 Lemmon	
                     '0701980732', # Comet C 2012 F6 Lemmon	
                     '0701980731', # Comet C 2012 F6 Lemmon	
                     '0672160431', # Comet C/2009 P1 (Garradd)	
                     '0672160432', # Comet C/2009 P1 (Garradd)	
                     '0672160631', # Comet C/2009 P1 (Garradd)	
                     '0672160632', # Comet C/2009 P1 (Garradd)	
                     '0672160931', # Comet C/2009 P1 (Garradd)	
                     '0672160932', # Comet C/2009 P1 (Garradd)	
                     '0800730701', # Star HD 3447 Observation repositioned after 3ks
                     ]
