site_name: EXOD Documentation
repo_url: "https://github.com/nx1/EXOD2"
site_url: "https://exod2.readthedocs.io"
nav:
  - Home: index.md
  - Plots: plots.md
theme:
  name: "material"
  logo: "images/exod_logo_transparent.png"
  palette:
    scheme: slate
  features:
    - navigation.instant


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true
