simbad_classifier = {'': '',
                  'X': 'Unknown', 'IR': 'Unknown', 'Radio': 'Unknown', 'MIR': 'Unknown',
                  'NIR': 'Unknown', 'HH': 'Unknown', 'HI': 'Unknown', 'HII': 'Unknown',
                  'LensedImage': 'Unknown', 'LensingEv': 'Unknown', 'Maser': 'Unknown',
                  'MolCld': 'Unknown', 'PartofCloud': 'Unknown', 'Radio(sub-mm)': 'Unknown',
                  'Blue': 'Unknown', 'Possible_lensImage': 'Unknown', 'Unknown': 'Unknown',
                  'Radio(mm)': 'Unknown', 'denseCore': 'Unknown', 'Radio(cm)': 'Unknown',
                  'UV': 'Unknown', 'PN': 'Unknown', 'PN?': 'Unknown', "EmObj": 'Unknown',
                  'DkNeb': 'Unknown', 'Transient': 'Unknown', 'Candidate_LensSystem': 'Unknown',
                  'FIR': 'Unknown', 'multiple_object': 'Unknown', 'GravLensSystem': 'Unknown',
                  'Bubble': 'Unknown', 'Cloud': 'Unknown', 'SFregion': 'Unknown',
                  'Inexistent': 'Unknown', 'gamma': 'Unknown', 'GravLens': 'Unknown',
                  'HVCld': 'Unknown', 'Candidate_Lens': 'Unknown', 'ISM': 'Unknown',
                  'Void': 'Unknown', 'RfNeb': 'Unknown', 'HIshell': 'Unknown', 'Outflow': 'Unknown',
                  'radioBurst': 'Unknown', 'Region': 'Unknown', 'Globule': 'Unknown',
                  'outflow?': 'Unknown', 'ComGlob': 'Unknown',
                  'GinCl': 'Galaxy', 'Galaxy': 'Galaxy', 'AGN': 'Galaxy', 'GiC': 'Galaxy', 'Sy1': 'Galaxy',
                  'Sy2': 'Galaxy', 'AGN_Candidate': 'Galaxy', 'QSO': 'Galaxy', 'Seyfert_1': 'Galaxy',
                  'Seyfert_2': 'Galaxy', 'LINER': 'Galaxy', 'EmG': 'Galaxy', 'RadioG': 'Galaxy', 'BClG': 'Galaxy',
                  'LSB_G': 'Galaxy', 'LensedG': 'Galaxy', 'LensedQ': 'Galaxy', 'GroupG': 'Galaxy',
                  'PartOfG': 'Galaxy', 'BLLac': 'Galaxy', 'GinPair': 'Galaxy', 'Possible_ClG': 'Galaxy',
                  'Possible_G': 'Galaxy', 'Possible_GrG': 'Galaxy', 'GinGroup': 'Galaxy', 'HII_G': 'Galaxy',
                  'Blazar': 'Galaxy', 'ClG': 'Galaxy', 'QSO_Candidate': 'Galaxy', 'Seyfert': 'Galaxy',
                  'Blazar_Candidate': 'Galaxy', 'StarburstG': 'Galaxy', 'IG': 'Galaxy', 'SuperClG': 'Galaxy',
                  'PartofG': 'Galaxy', 'Compact_Gr_G': 'Galaxy', 'PairG': 'Galaxy', 'BLLac_Candidate': 'Galaxy',
                  'BlueCompG': 'Galaxy',
                  'Orion_V*': 'Star', 'TTau*': 'Star', 'EB*': 'Star', 'YSO': 'Star', 'SB*': 'Star', '**': 'Star',
                  'Star': 'Star', 'RotV*': 'Star', 'Candidate_RGB*': 'Star', 'low-mass*': 'Star', 'V*': 'Star',
                  'PulsV*': 'Star', 'AGB*': 'Star', 'S*': 'Star', 'Candidate_YSO': 'Star', 'PM*': 'Star',
                  'Irregular_V*': 'Star', 'Em*': 'Star', 'LPV*': 'Star', 'Mira': 'Star', 'WR*': 'Star',
                  'Pec*': 'Star', 'Planet?': 'Star', 'Planet': 'Star', 'Eruptive*': 'Star', 'Cl*': 'Star',
                  'OpCl': 'Star', 'Assoc*': 'Star', 'PulsV*WVir': 'Star', 'PulsV*bCep': 'Star', 'RRLyr': 'Star',
                  'C*': 'Star', 'EllipVar': 'Star', 'Candidate_EB*': 'Star', 'Candidate_PulsV*WVir': 'Star',
                  'Candidate_LP*': 'Star', 'pulsV*SX': 'Star', 'Candidate_RSG*': 'Star', 'BYDra': 'Star',
                  'Be*': 'Star', 'Candidate_RRLyr': 'Star', 'BlueSG*': 'Star', 'Erupt*RCrB': 'Star', 'RGB*': 'Star',
                  'RSCVn': 'Star', 'gammaDor': 'Star', 'Cl*?': 'Star', 'Candidate_C*': 'Star', 'HB*': 'Star',
                  'Cepheid': 'Star', 'Ae*': 'Star', 'Candidate_TTau*': 'Star', 'deltaCep': 'Star',
                  'HotSubdwarf': 'Star', 'Candidate_AGB*': 'Star', 'YellowSG*': 'Star', 'Symbiotic*': 'Star',
                  'PulsV*delSct': 'Star', 'BlueStraggler': 'Star', 'Candidate_post-AGB*': 'Star',
                  'RotV*alf2CVn': 'Star', 'OH/IR': 'Star', 'V*?': 'Star', 'Candidate_BSG*': 'Star',
                  'RedSG*': 'Star', 'Candidate_brownD*': 'Star', 'Candidate_Mi*': 'Star', 'Candidate_HB*': 'Star',
                  'Candidate_Be*': 'Star', 'Candidate_SN*': 'Star', 'brownD*': 'Star', 'SG*': 'Star',
                  'PulsV*RVTau': 'Star', 'Candidate_WR*': 'Star', 'HV*': 'Star', 'Candidate_Hsd': 'Star',
                  'Candidate_Ae*': 'Star', 'Candidate_Cepheid': 'Star', 'post-AGB*': 'Star', 'Candidate_**': 'Star',
                  'Candidate_Symb*': 'Star', 'Candidate_S*': 'Star', 'Candidate_SG*': 'Star',
                  'Candidate_low-mass*': 'Star',
                  'GlCl': 'CompactObject', 'GlCl?': 'CompactObject', 'Pulsar': 'CompactObject',
                  'ULX': 'CompactObject', 'ULX?': 'CompactObject', 'HMXB': 'CompactObject',
                  'Candidate_HMXB': 'CompactObject', 'LMXB': 'CompactObject', 'Candidate_LMXB': 'CompactObject',
                  'Nova': 'CompactObject', 'CataclyV*': 'CompactObject', 'XB': 'CompactObject',
                  'SNR': 'CompactObject', 'SNR?': 'CompactObject', 'Candidate_WD*': 'CompactObject',
                  'WD*': 'CompactObject', 'SN': 'CompactObject', 'gammaBurst': 'CompactObject',
                  'Candidate_XB*': 'CompactObject', 'Candidate_BH': 'CompactObject', 'NS': 'CompactObject',
                  'Candidate_NS': 'CompactObject', 'Neutron*': 'CompactObject', 'Candidate_CV*': 'CompactObject',
                  'Candidate_Nova': 'CompactObject','Seyfert2': 'Galaxy','Seyfert1': 'Galaxy'}
