simbad_classifier = {'' : '',
                     'X' : 'Unidentified',
                     'IR' : 'Unidentified',
                     'Radio' : 'Unidentified',
                     'MIR' : 'Unidentified',
                     'NIR' : 'Unidentified',
                     'HH' : 'Unidentified',
                     'HI' : 'Unidentified',
                     'HII' : 'Unidentified',
                     'HighPM*' : 'Unidentified',
                     'LensedImage' : 'Unidentified',
                     'LensingEv' : 'Unidentified',
                     'Maser' : 'Unidentified',
                     'MolCld' : 'Unidentified',
                     'PartofCloud' : 'Unidentified',
                     'Radio(sub-mm)' : 'Unidentified',
                     'Blue' : 'Unidentified',
                     'Possible_lensImage' : 'Unidentified',
                     'Unidentified' : 'Unidentified',
                     'Radio(mm)' : 'Unidentified',
                     'denseCore' : 'Unidentified',
                     'Radio(cm)' : 'Unidentified',
                     'UV' : 'Unidentified',
                     'PN' : 'Unidentified',
                     'PN?' : 'Unidentified',
                     'EmObj' : 'Unidentified',
                     'DkNeb' : 'Unidentified',
                     'Transient' : 'Unidentified',
                     'Candidate_LensSystem' : 'Unidentified',
                     'FIR' : 'Unidentified',
                     'multiple_object' : 'Unidentified',
                     'GravLensSystem' : 'Unidentified',
                     'Bubble' : 'Unidentified',
                     'Cloud' : 'Unidentified',
                     'SFregion' : 'Unidentified',
                     'Inexistent' : 'Unidentified',
                     'gamma' : 'Unidentified',
                     'GravLens' : 'Unidentified',
                     'HVCld' : 'Unidentified',
                     'Candidate_Lens' : 'Unidentified',
                     'ISM' : 'Unidentified',
                     'Void' : 'Unidentified',
                     'RfNeb' : 'Unidentified',
                     'HIshell' : 'Unidentified',
                     'Outflow' : 'Unidentified',
                     'radioBurst' : 'Unidentified',
                     'Region' : 'Unidentified',
                     'Globule' : 'Unidentified',
                     'outflow?' : 'Unidentified',
                     'ComGlob' : 'Unidentified',
                     'GinCl' : 'Galaxy',
                     'Galaxy' : 'Galaxy',
                     'AGN' : 'Galaxy',
                     'GiC' : 'Galaxy',
                     'Sy1' : 'Galaxy',
                     'Sy2' : 'Galaxy',
                     'AGN_Candidate' : 'Galaxy',
                     'QSO' : 'Galaxy',
                     'Seyfert_1' : 'Galaxy',
                     'Seyfert_2' : 'Galaxy',
                     'LINER' : 'Galaxy',
                     'EmG' : 'Galaxy',
                     'RadioG' : 'Galaxy',
                     'BClG' : 'Galaxy',
                     'LSB_G' : 'Galaxy',
                     'LensedG' : 'Galaxy',
                     'LensedQ' : 'Galaxy',
                     'GroupG' : 'Galaxy',
                     'PartOfG' : 'Galaxy',
                     'BLLac' : 'Galaxy',
                     'GinPair' : 'Galaxy',
                     'Possible_ClG' : 'Galaxy',
                     'Possible_G' : 'Galaxy',
                     'Possible_GrG' : 'Galaxy',
                     'GinGroup' : 'Galaxy',
                     'HII_G' : 'Galaxy',
                     'Blazar' : 'Galaxy',
                     'ClG' : 'Galaxy',
                     'QSO_Candidate' : 'Galaxy',
                     'Seyfert' : 'Galaxy',
                     'Blazar_Candidate' : 'Galaxy',
                     'StarburstG' : 'Galaxy',
                     'IG' : 'Galaxy',
                     'SuperClG' : 'Galaxy',
                     'PartofG' : 'Galaxy',
                     'Compact_Gr_G' : 'Galaxy',
                     'PairG' : 'Galaxy',
                     'BLLac_Candidate' : 'Galaxy',
                     'BlueCompG' : 'Galaxy',
                     'Orion_V*' : 'Star',
                     'TTau*' : 'Star',
                     'EB*' : 'Star',
                     'YSO' : 'Star',
                     'SB*' : 'Star',
                     '**' : 'Star',
                     'Star' : 'Star',
                     'RotV*' : 'Star',
                     'Candidate_RGB*' : 'Star',
                     'low-mass*' : 'Star',
                     'V*' : 'Star',
                     'PulsV*' : 'Star',
                     'AGB*' : 'Star',
                     'S*' : 'Star',
                     'Candidate_YSO' : 'Star',
                     'PM*' : 'Star',
                     'Irregular_V*' : 'Star',
                     'Em*' : 'Star',
                     'LPV*' : 'Star',
                     'Mira' : 'Star',
                     'WR*' : 'Star',
                     'Pec*' : 'Star',
                     'Planet?' : 'Star',
                     'Planet' : 'Star',
                     'Eruptive*' : 'Star',
                     'Cl*' : 'Star',
                     'OpCl' : 'Star',
                     'Assoc*' : 'Star',
                     'PulsV*WVir' : 'Star',
                     'PulsV*bCep' : 'Star',
                     'RRLyr' : 'Star',
                     'C*' : 'Star',
                     'EllipVar' : 'Star',
                     'Candidate_EB*' : 'Star',
                     'Candidate_PulsV*WVir' : 'Star',
                     'Candidate_LP*' : 'Star',
                     'pulsV*SX' : 'Star',
                     'Candidate_RSG*' : 'Star',
                     'BYDra' : 'Star',
                     'Be*' : 'Star',
                     'Candidate_RRLyr' : 'Star',
                     'BlueSG*' : 'Star',
                     'Erupt*RCrB' : 'Star',
                     'RGB*' : 'Star',
                     'RSCVn' : 'Star',
                     'gammaDor' : 'Star',
                     'Cl*?' : 'Star',
                     'Candidate_C*' : 'Star',
                     'HB*' : 'Star',
                     'Cepheid' : 'Star',
                     'Ae*' : 'Star',
                     'Candidate_TTau*' : 'Star',
                     'deltaCep' : 'Star',
                     'HotSubdwarf' : 'Star',
                     'Candidate_AGB*' : 'Star',
                     'YellowSG*' : 'Star',
                     'Symbiotic*' : 'Star',
                     'PulsV*delSct' : 'Star',
                     'BlueStraggler' : 'Star',
                     'Candidate_post-AGB*' : 'Star',
                     'RotV*alf2CVn' : 'Star',
                     'OH/IR' : 'Star',
                     'V*?' : 'Star',
                     'Candidate_BSG*' : 'Star',
                     'RedSG*' : 'Star',
                     'Candidate_brownD*' : 'Star',
                     'Candidate_Mi*' : 'Star',
                     'Candidate_HB*' : 'Star',
                     'Candidate_Be*' : 'Star',
                     'Candidate_SN*' : 'Star',
                     'brownD*' : 'Star',
                     'SG*' : 'Star',
                     'PulsV*RVTau' : 'Star',
                     'Candidate_WR*' : 'Star',
                     'HV*' : 'Star',
                     'Candidate_Hsd' : 'Star',
                     'Candidate_Ae*' : 'Star',
                     'Candidate_Cepheid' : 'Star',
                     'post-AGB*' : 'Star',
                     'Candidate_**' : 'Star',
                     'Candidate_Symb*' : 'Star',
                     'Candidate_S*' : 'Star',
                     'Candidate_SG*' : 'Star',
                     'Candidate_low-mass*' : 'Star',
                     'OrionV*'   : 'Star',
                     'TTauri*'   : 'Star',
                     'GlCl' : 'CompactObject',
                     'GlCl?' : 'CompactObject',
                     'Pulsar' : 'CompactObject',
                     'ULX' : 'CompactObject',
                     'ULX?' : 'CompactObject',
                     'HMXB' : 'CompactObject',
                     'Candidate_HMXB' : 'CompactObject',
                     'LMXB' : 'CompactObject',
                     'Candidate_LMXB' : 'CompactObject',
                     'Nova' : 'CompactObject',
                     'CataclyV*' : 'CompactObject',
                     'XB' : 'CompactObject',
                     'SNR' : 'CompactObject',
                     'SNR?' : 'CompactObject',
                     'Candidate_WD*' : 'CompactObject',
                     'WD*' : 'CompactObject',
                     'SN' : 'CompactObject',
                     'gammaBurst' : 'CompactObject',
                     'Candidate_XB*' : 'CompactObject',
                     'Candidate_BH' : 'CompactObject',
                     'NS' : 'CompactObject',
                     'Candidate_NS' : 'CompactObject',
                     'Neutron*' : 'CompactObject',
                     'Candidate_CV*' : 'CompactObject',
                     'Candidate_Nova' : 'CompactObject',
                     'Seyfert2' : 'Galaxy',
                     'Seyfert1' : 'Galaxy'}

astronomical_classifications = {
    "Stars": {
        "General": ["Star", "BlueSG*", "RedSG*", "YellowSG*"],
        "Variable": ["V*", "Irregular_V*", "EllipVar", "Cepheid", "Mira", "RotV*", "PulsV*", "PulsV*RVTau", "PulsV*WVir", "PulsV*bCep", "PulsV*delSct", "pulsV*SX"],
        "Binary": ["**", "EB*", "BYDra", "RSCVn"],
        "Eruptive": ["Eruptive*", "Erupt*RCrB", "OrionV*", "Orion_V*"],
        "Symbiotic": ["Symbiotic*", "Symb*"],
        "Young Stellar Objects": ["YSO", "TTau*", "TTauri*"],
        "Evolved": ["AGB*", "post-AGB*", "C*", "S*", "RGB*", "HB*"],
        "Wolf-Rayet": ["WR*"],
        "Brown Dwarfs": ["brownD*", "gammaDor"],
        "Degenerate": ["WD*", "Neutron*", "NS"]
    },
    "Star Candidates": {
        "General": ["Candidate_*", "Candidate_**", "Candidate_YSO", "Candidate_TTau*", "Candidate_brownD*"],
        "Variable": ["Candidate_V*", "Candidate_EB*", "Candidate_Cepheid", "Candidate_HB*", "Candidate_LP*", "Candidate_Mi*", "Candidate_PulsV*WVir", "Candidate_RGB*", "Candidate_RRLyr", "Candidate_SG*"],
        "Binary": ["EB*_Candidate", "Candidate_EB*", "Candidate_XB*"],
        "Eruptive": ["Candidate_Symb*"],
        "Young Stellar Objects": ["Candidate_YSO", "Candidate_TTau*", "TTauri*"],
        "Evolved": ["Candidate_AGB*", "Candidate_post-AGB*", "Candidate_C*", "Candidate_S*"],
        "Wolf-Rayet": ["Candidate_WR*"],
        "Brown Dwarfs": ["Candidate_brownD*"],
        "Degenerate": ["Candidate_WD*", "Candidate_NS", "Candidate_Nova"]
    },
    "Galaxies": {
        "General": ["Galaxy", "StarburstG"],
        "Active": ["AGN", "BLLac", "Seyfert", "Seyfert1", "Seyfert2", "Blazar", "LINER"],
        "Radio": ["RadioG"],
        "Infrared": ["IR", "MIR", "NIR"],
        "Ultra-luminous X-ray sources": ["ULX"],
        "Lens": ["LensedG", "GravLens", "GravLensSystem"]
    },
    "Galactic Structures": {
        "Clusters": ["ClG", "BClG", "SuperClG", "Possible_ClG", "Possible_GrG"],
        "Groups": ["GroupG", "GinGroup", "GinCl"],
        "Associations": ["Assoc*"],
        "Pairs": ["PairG", "GinPair"]
    },
    "Nebulae": {
        "General": ["Neb", "EmNeb", "RfNeb"],
        "Planetary": ["PN", "PN?", "PN?_Candidate"],
        "H II Regions": ["HII", "HII_G"],
        "Dark": ["DkNeb", "Globule"],
        "Reflection": ["RfNeb"],
        "Supernova Remnants": ["SNR", "SNR?", "SNR?_Candidate"]
    },
    "Variable Stars": {
        "General": ["V*", "Irregular_V*", "PulsV*"],
        "Eruptive": ["Eruptive*", "Erupt*RCrB"],
        "Cataclysmic": ["CataclyV*", "Nova", "Pulsar"],
        "Pulsating": ["PulsV*RVTau", "PulsV*WVir", "PulsV*bCep", "PulsV*delSct", "pulsV*SX"]
    },
    "Exotic Objects": {
        "Black Holes": ["BH", "Candidate_BH"],
        "Neutron Stars": ["NS", "Candidate_NS"],
        "Quasars": ["QSO", "QSO_Candidate"]
    },
    "Miscellaneous": {
        "Clusters": ["Cl*", "GlCl"],
        "Clouds": ["Cloud", "MolCld", "HVCld"],
        "Globules": ["Globule"],
        "Associations": ["Assoc*", "GiC"],
        "Unknown": ["Inexistent", "Unknown_Candidate"],
        "Infrared": ["IR", "MIR"],
        "Radio": ["Radio", "Radio(cm)", "Radio(mm)", "Radio(sub-mm)"]
    }
}


def get_reversed_classifications():
    astronomical_classifications_rev = {}
    for k1, d1 in astronomical_classifications.items():
        for k2, simbad_classes in d1.items():
            for s in simbad_classes:
                astronomical_classifications_rev[s] = [k1,k2]
    return astronomical_classifications_rev
