simbad_classifier = {'' : '',
                     'X' : 'Unidentified',
                     'IR' : 'Unidentified',
                     'Radio' : 'Unidentified',
                     'MIR' : 'Unidentified',
                     'NIR' : 'Unidentified',
                     'HH' : 'Unidentified',
                     'HI' : 'Unidentified',
                     'HII' : 'Unidentified',
                     'HighPM*' : 'Unidentified',
                     'LensedImage' : 'Unidentified',
                     'LensingEv' : 'Unidentified',
                     'Maser' : 'Unidentified',
                     'MolCld' : 'Unidentified',
                     'PartofCloud' : 'Unidentified',
                     'Radio(sub-mm)' : 'Unidentified',
                     'Blue' : 'Unidentified',
                     'Possible_lensImage' : 'Unidentified',
                     'Unidentified' : 'Unidentified',
                     'Radio(mm)' : 'Unidentified',
                     'denseCore' : 'Unidentified',
                     'Radio(cm)' : 'Unidentified',
                     'UV' : 'Unidentified',
                     'PN' : 'Unidentified',
                     'PN?' : 'Unidentified',
                     'EmObj' : 'Unidentified',
                     'DkNeb' : 'Unidentified',
                     'Transient' : 'Unidentified',
                     'Candidate_LensSystem' : 'Unidentified',
                     'FIR' : 'Unidentified',
                     'multiple_object' : 'Unidentified',
                     'GravLensSystem' : 'Unidentified',
                     'Bubble' : 'Unidentified',
                     'Cloud' : 'Unidentified',
                     'SFregion' : 'Unidentified',
                     'Inexistent' : 'Unidentified',
                     'gamma' : 'Unidentified',
                     'GravLens' : 'Unidentified',
                     'HVCld' : 'Unidentified',
                     'Candidate_Lens' : 'Unidentified',
                     'ISM' : 'Unidentified',
                     'Void' : 'Unidentified',
                     'RfNeb' : 'Unidentified',
                     'HIshell' : 'Unidentified',
                     'Outflow' : 'Unidentified',
                     'radioBurst' : 'Unidentified',
                     'Region' : 'Unidentified',
                     'Globule' : 'Unidentified',
                     'outflow?' : 'Unidentified',
                     'ComGlob' : 'Unidentified',
                     'GinCl' : 'Galaxy',
                     'Galaxy' : 'Galaxy',
                     'AGN' : 'Galaxy',
                     'GiC' : 'Galaxy',
                     'Sy1' : 'Galaxy',
                     'Sy2' : 'Galaxy',
                     'AGN_Candidate' : 'Galaxy',
                     'QSO' : 'Galaxy',
                     'Seyfert_1' : 'Galaxy',
                     'Seyfert_2' : 'Galaxy',
                     'LINER' : 'Galaxy',
                     'EmG' : 'Galaxy',
                     'RadioG' : 'Galaxy',
                     'BClG' : 'Galaxy',
                     'LSB_G' : 'Galaxy',
                     'LensedG' : 'Galaxy',
                     'LensedQ' : 'Galaxy',
                     'GroupG' : 'Galaxy',
                     'PartOfG' : 'Galaxy',
                     'BLLac' : 'Galaxy',
                     'GinPair' : 'Galaxy',
                     'Possible_ClG' : 'Galaxy',
                     'Possible_G' : 'Galaxy',
                     'Possible_GrG' : 'Galaxy',
                     'GinGroup' : 'Galaxy',
                     'HII_G' : 'Galaxy',
                     'Blazar' : 'Galaxy',
                     'ClG' : 'Galaxy',
                     'QSO_Candidate' : 'Galaxy',
                     'Seyfert' : 'Galaxy',
                     'Blazar_Candidate' : 'Galaxy',
                     'StarburstG' : 'Galaxy',
                     'IG' : 'Galaxy',
                     'SuperClG' : 'Galaxy',
                     'PartofG' : 'Galaxy',
                     'Compact_Gr_G' : 'Galaxy',
                     'PairG' : 'Galaxy',
                     'BLLac_Candidate' : 'Galaxy',
                     'BlueCompG' : 'Galaxy',
                     'Orion_V*' : 'Star',
                     'TTau*' : 'Star',
                     'EB*' : 'Star',
                     'YSO' : 'Star',
                     'SB*' : 'Star',
                     '**' : 'Star',
                     'Star' : 'Star',
                     'RotV*' : 'Star',
                     'Candidate_RGB*' : 'Star',
                     'low-mass*' : 'Star',
                     'V*' : 'Star',
                     'PulsV*' : 'Star',
                     'AGB*' : 'Star',
                     'S*' : 'Star',
                     'Candidate_YSO' : 'Star',
                     'PM*' : 'Star',
                     'Irregular_V*' : 'Star',
                     'Em*' : 'Star',
                     'LPV*' : 'Star',
                     'Mira' : 'Star',
                     'WR*' : 'Star',
                     'Pec*' : 'Star',
                     'Planet?' : 'Star',
                     'Planet' : 'Star',
                     'Eruptive*' : 'Star',
                     'Cl*' : 'Star',
                     'OpCl' : 'Star',
                     'Assoc*' : 'Star',
                     'PulsV*WVir' : 'Star',
                     'PulsV*bCep' : 'Star',
                     'RRLyr' : 'Star',
                     'C*' : 'Star',
                     'EllipVar' : 'Star',
                     'Candidate_EB*' : 'Star',
                     'Candidate_PulsV*WVir' : 'Star',
                     'Candidate_LP*' : 'Star',
                     'pulsV*SX' : 'Star',
                     'Candidate_RSG*' : 'Star',
                     'BYDra' : 'Star',
                     'Be*' : 'Star',
                     'Candidate_RRLyr' : 'Star',
                     'BlueSG*' : 'Star',
                     'Erupt*RCrB' : 'Star',
                     'RGB*' : 'Star',
                     'RSCVn' : 'Star',
                     'gammaDor' : 'Star',
                     'Cl*?' : 'Star',
                     'Candidate_C*' : 'Star',
                     'HB*' : 'Star',
                     'Cepheid' : 'Star',
                     'Ae*' : 'Star',
                     'Candidate_TTau*' : 'Star',
                     'deltaCep' : 'Star',
                     'HotSubdwarf' : 'Star',
                     'Candidate_AGB*' : 'Star',
                     'YellowSG*' : 'Star',
                     'Symbiotic*' : 'Star',
                     'PulsV*delSct' : 'Star',
                     'BlueStraggler' : 'Star',
                     'Candidate_post-AGB*' : 'Star',
                     'RotV*alf2CVn' : 'Star',
                     'OH/IR' : 'Star',
                     'V*?' : 'Star',
                     'Candidate_BSG*' : 'Star',
                     'RedSG*' : 'Star',
                     'Candidate_brownD*' : 'Star',
                     'Candidate_Mi*' : 'Star',
                     'Candidate_HB*' : 'Star',
                     'Candidate_Be*' : 'Star',
                     'Candidate_SN*' : 'Star',
                     'brownD*' : 'Star',
                     'SG*' : 'Star',
                     'PulsV*RVTau' : 'Star',
                     'Candidate_WR*' : 'Star',
                     'HV*' : 'Star',
                     'Candidate_Hsd' : 'Star',
                     'Candidate_Ae*' : 'Star',
                     'Candidate_Cepheid' : 'Star',
                     'post-AGB*' : 'Star',
                     'Candidate_**' : 'Star',
                     'Candidate_Symb*' : 'Star',
                     'Candidate_S*' : 'Star',
                     'Candidate_SG*' : 'Star',
                     'Candidate_low-mass*' : 'Star',
                     'OrionV*'   : 'Star',
                     'TTauri*'   : 'Star',
                     'GlCl' : 'CompactObject',
                     'GlCl?' : 'CompactObject',
                     'Pulsar' : 'CompactObject',
                     'ULX' : 'CompactObject',
                     'ULX?' : 'CompactObject',
                     'HMXB' : 'CompactObject',
                     'Candidate_HMXB' : 'CompactObject',
                     'LMXB' : 'CompactObject',
                     'Candidate_LMXB' : 'CompactObject',
                     'Nova' : 'CompactObject',
                     'CataclyV*' : 'CompactObject',
                     'XB' : 'CompactObject',
                     'SNR' : 'CompactObject',
                     'SNR?' : 'CompactObject',
                     'Candidate_WD*' : 'CompactObject',
                     'WD*' : 'CompactObject',
                     'SN' : 'CompactObject',
                     'gammaBurst' : 'CompactObject',
                     'Candidate_XB*' : 'CompactObject',
                     'Candidate_BH' : 'CompactObject',
                     'NS' : 'CompactObject',
                     'Candidate_NS' : 'CompactObject',
                     'Neutron*' : 'CompactObject',
                     'Candidate_CV*' : 'CompactObject',
                     'Candidate_Nova' : 'CompactObject',
                     'Seyfert2' : 'Galaxy',
                     'Seyfert1' : 'Galaxy',
                     'LP*_Candidate' : 'Star',
                     'YSO_Candidate' : 'Star',
                     'ULX?_Candidate' : 'CompactObject',
                     'WD*_Candidate' : 'CompactObject',
                     'SNR?_Candidate' : 'CompactObject',
                     'RGB*_Candidate': 'Star',
                     'G_Candidate' : 'Galaxy',
                     'PN?_Candidate' : 'Unidentified', # Planetary Nebula
                     'Unknown_Candidate' : 'Unidentified',
                     'RSG*_Candidate' : 'Star',
                     'Nova_Candidate' : 'CompactObject',
                     'brownD*_Candidate' : 'Star',
                     'EB*_Candidate' : 'Star',
                     'Be*_Candidate' : 'Star',
                     'HMXB_Candidate' : 'CompactObject',
                     'Cepheid_Candidate' : 'Star',
                     'GalNeb' : 'Galaxy',
                     'LMXB_Candidate' : 'CompactObject',
                     'GlCl?_Candidate' : 'CompactObject',
                     'HB*_Candidate' : 'Star',
                     'Planet?_Candidate' : 'Star',
                     'Hsd_Candidate' : 'Star',
                     'BSG*_Candidate' : 'Star',
                     'AGB*_Candidate' : 'Star',
                     'XB*_Candidate' : 'CompactObject',
                     'ClG_Candidate' : 'Galaxy',
                     'OH_Candidate' : 'Star',
                     'Lens_Candidate' : 'Unidentified',
                     'low-mass*_Candidate' : 'Star',
                     'SN*_Candidate' : 'CompactObject',
                     'V*?_Candidate' : 'Star',
                     'EclBin' : 'Star',
                     'LongPeriodV*_Candidate': 'Star',
                     'GtowardsCl': 'Galaxy',
                     'LongPeriodV*': 'Star',
                     'WhiteDwarf_Candidate': 'CompactObject',
                     'RRLyrae': 'Star',
                     'BrightestCG': 'Galaxy',
                     'Variable*': 'Star',
                     'BYDraV*': 'Star',
                     'EmissionG': 'Galaxy',
                     'RSCVnV*': 'Star',
                     'Low-Mass*': 'Star',
                     'FarIR': 'Unidentified',
                     'Infrared*': 'Unidentified',
                     'ChemPec*': 'Star',
                     'delSctV*': 'Star',
                     'WhiteDwarf': 'CompactObject',
                     'HIIReg': 'Unidentified',
                     'HorBranch*': 'Star',
                     'EmLine*': 'Star',
                     'HotSubdwarf_Candidate': 'Star',
                     'smmRad': 'Unidentified',
                     'DarkNeb': 'Unidentified',
                     'Unknown': 'Unidentified',
                     'GlobCluster': 'Galaxy',
                     'NearIR': 'Unidentified',
                     'blue': 'Unidentified',
                     'Supernova': 'CompactObject',
                     'ClassicalCep': 'Star',
                     'GlobCluster_Candidate': 'Galaxy',
                     'Cluster*': 'Star',
                     'GtowardsGroup': 'Galaxy',
                     'BrownD*_Candidate': 'Star',
                     'LowSurfBrghtG': 'Galaxy',
                     'PlanetaryNeb': 'Unidentified',
                     'RRLyrae_Candidate': 'Star',
                     'mmRad': 'Unidentified',
                     'RedSG_Candidate': 'Star',
                     'Galaxy_Candidate': 'Galaxy',
                     'PlanetaryNeb_Candidate': 'Unidentified',
                     'Planet_Candidate': 'Unidentified',
                     'OpenCluster': 'Unidentified',
                     'Association': 'Unidentified',
                     'cmRad': 'Unidentified',
                     'EclBin_Candidate': 'Star',
                     'MainSequence*': 'Star',
                     'Cluster*_Candidate': 'Star',
                     'HorBranch*_Candidate': 'Star',
                     'MidIR': 'Unidentified',
                     'HerbigHaroObj': 'Unidentified',
                     'Supernova_Candidate': 'CompactObject',
                     'Type2Cep': 'Star',
                     'Optical': 'Unidentified',
                     'Blend': 'Unidentified',
                     'BrownD*': 'Star',
                     'HighVel*': 'Star',
                     'OH/IR*' : 'Star',
                     'RedSG' : 'Star',
                     'CataclyV*_Candidate' : 'CompactObject',
                     'SNRemnant' : 'CompactObject',
                     'S*_Candidate' : 'Star',
                     'HighMassXBin' : 'CompactObject',
                     'C*_Candidate' : 'Star',
                     'WolfRayet*' : 'Star',
                     'gammaDorV*' : 'Star',
                     'SNRemnant_Candidate' : 'CompactObject',
                     'XrayBin' : 'CompactObject',
                     'InteractingG' : 'Galaxy',
                     'GravLens_Candidate' : 'Unidentified',
                     'RefNeb' : 'Unidentified',
                     'BlueSG' : 'Star',
                     'GroupG_Candidate' : 'Galaxy',
                     'alf2CVnV*' : 'Star',
                     'HIIG' : 'Galaxy',
                     'LensedImage_Candidate' : 'Unidentified',
                     'Variable*_Candidate' : 'Star',
                     'GravLensSystem_Candidate' : 'Unidentified',
                     'SB*_Candidate' : 'Star',
                     'IrregularV*' : 'Star',
                     'LowMassXBin' : 'CompactObject',
                     'BlueStraggler_Candidate' : 'Star',
                     'post-AGB*_Candidate' : 'Star',
                     'BlueCompactG' : 'Galaxy',
                     'StarFormingReg' : 'Unidentified',
                     'RVTauV*' : 'Star',
                     'SXPheV*' : 'Star',
                     'Outflow_Candidate' : 'Unidentified',
                     'Supergiant' : 'Star',
                     'bCepV*' : 'Star',
                     'BlueSG_Candidate' : 'Star',
                     'Type2Cep_Candidate' : 'Star',
                     'TTauri*_Candidate' : 'Star',
                     'YellowSG' : 'Star',
                     'GravWaveEvent' : 'Unidentified',
                     'ULX_Candidate' : 'CompactObject',
                     'RCrBV*' : 'Star',
                     'XrayBin_Candidate' : 'CompactObject',
                     'bCepV*_Candidate' : 'Star',
                     'WolfRayet*_Candidate' : 'Star',
                     'Stream' : 'Unidentified',
                     'MouvGroup' : 'Unidentified',
                     'Low-Mass*_Candidate' : 'Star',
                     'Mira_Candidate' : 'Star',
                     'HighMassXBin_Candidate' : 'CompactObject',
                     'Filament' : 'Unidentified',
                     'Supergiant_Candidate' : 'Star',
                     '**_Candidate' : 'Star',
                     'Ae*_Candidate' : 'Star',
                     'EllipVar_Candidate' : 'Star',
                     'YellowSG_Candidate' : 'Star',
                     'LowMassXBin_Candidate' : 'CompactObject',
                     'protoClG' : 'Star',
                     'Symbiotic*_Candidate' : 'Star',
                     'Massiv*': 'Star',
                     'MainSequence*_Candidate' : 'Star',
                     'OH/IR*_Candidate' : 'Star',
                     'ChemPec*_Candidate' : 'Star',
                     'BlackHole_Candidate' : 'CompactObject',
                     'Neutron*_Candidate' : 'CompactObject',
                     'Evolved*_Candidate' : 'Star',
                     'RCrBV*_Candidate' : 'Star',
                     'protoClG_Candidate' : 'Star',
                     'Gravitation' : 'Unidentified',
                     'alf2CVnV*_Candidate' : 'Star',
                     'BlackHole' : 'CompactObject',
                     'RSCVnV*_Candidate' : 'Star',
                     'BYDraV*_Candidate' : 'Star',
                     'Infrared': 'Unidentified',
                     'RRLyr_Candidate': 'Star',
                     'CV*_Candidate': 'CompactObject',
                     'PulsV*WVir_Candidate': 'Star',
                     'NS_Candidate': 'CompactObject',
                     'GrG_Candidate': 'Galaxy',
                     'Mi*_Candidate': 'Star',
                     'lensImage_Candidate': 'Unidentified',
                     'LensSystem_Candidate': 'Unidentified',
                     'TTau*_Candidate': 'Star',
                     'outflow?_Candidate': 'Unidentified',
                     'YSG*_Candidate': 'Star',
                     'BH_Candidate': 'CompactObject',
                     'BSS_Candidate': 'Star',
                     'El*_Candidate': 'Star',
                     'WR*_Candidate': 'Star'}
